#change rules - team codding
opentibiabr/myaac pull request #42
Opened 2023-11-20 01:00 UTC by LeoTKBR

**Rules GIF:**
![rulesDemo](https://github.com/opentibiabr/myaac/assets/41605307/e18c123d-0e61-4cde-bce3-336b823f4f5c)
<br><br>
**Team GIF:**
![staffTeam](https://github.com/opentibiabr/myaac/assets/41605307/f5b53f09-1c34-408a-9244-4ad7127e1f89)

2023-11-20 03:02 UTC, LeoTKBR commented
#Fix serverinfo informations

![serverInfo](https://github.com/opentibiabr/myaac/assets/41605307/6e37ccbb-8b69-425b-a88e-878e0d8efe93)

2023-11-20 04:05 UTC, LeoTKBR commented
#fix hover buttons
![hoverFix](https://github.com/opentibiabr/myaac/assets/41605307/b8c25fcf-5eb3-456f-89a2-3f51e436760a)

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +$redSkullLength = isset($config['lua']['redSkullDuration']) ? $config['lua']['redSkullDuration'] : NULL;
nós podemos usar a variável configLua('redSkullDuration') e utilizar a seguinte condição:
```suggestion
$redSkullLength = $configLua['redSkullDuration'] ?? null;
```

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +$blackSkull = true;
deixe essa linha como false, se não, sempre será true.
```suggestion
$blackSkull = false;
```

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'serverIp' => str_replace('/', '', str_replace('http://', '', $config['lua']['ip'])),
em alguns casos, devido a cloudflare, é necessário deixar o ip da máquina real. assim, o ip ficará visivel para todos.
acho que pode ser criar uma nova config, chamada urlServerInfo.

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'dailyFragsToRedSkull' => isset($config['lua']['dayKillsToRedSkull']) ? $config['lua']['dayKillsToRedSkull'] : (isset($config['lua']['dayKillsToRedSkull']) ? $config['lua']['dayKillsToRedSkull']
redundância na condição. sempre valida por 'dayKillsToRedSkull'
```suggestion
    'dailyFragsToRedSkull' => configLua('dayKillsToRedSkull') ?? null),
```

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'weeklyFragsToRedSkull' => isset($config['lua']['weekKillsToRedSkull']) ? $config['lua']['weekKillsToRedSkull'] : (isset($config['lua']['weekKillsToRedSkull']) ? $config['lua']['weekKillsToRedSku
redundância na condição. sempre valida por 'weekKillsToRedSkull'
```suggestion
    'weeklyFragsToRedSkull' => configLua('weekKillsToRedSkull') ?? null),
```

2023-11-20 11:49 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'monthlyFragsToRedSkull' => isset($config['lua']['monthKillsToRedSkull']) ? $config['lua']['monthKillsToRedSkull'] : (isset($config['lua']['monthKillsToRedSkull']) ? $config['lua']['monthKillsToR
redundância na condição. sempre valida por 'weekKillsToRedSkull'
```suggestion
    'monthlyFragsToRedSkull' => configLua('monthKillsToRedSkull') ?? null),
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +$redSkullLength = $configLua('redSkullDuration') ?? null;
```suggestion
$redSkullLength = configLua('redSkullDuration') ?? null;
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +$blackSkullLength = isset($config['lua']['blackSkullDuration']) ? $config['lua']['blackSkullDuration'] : NULL;
```suggestion
$blackSkullLength = configLua('blackSkullDuration') : null;
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    $blackSkullLength = $config['lua']['blackSkullDuration'];
```suggestion
    $blackSkullLength = configLua('blackSkullDuration');
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    $blackSkullLength = eval('return ' . $config['lua']['blackSkullDuration'] . ';');
```suggestion
    $blackSkullLength = eval('return ' . configLua('blackSkullDuration') . ';');
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'serverIp' => str_replace(array('http://', 'https://'), '', $config['lua']['url']),
```suggestion
    'serverIp' => str_replace(['http://', 'https://'], '', configLua('url'),
```

2023-11-20 15:34 UTC, elsongabriel commented on system/templates/serverinfo.html.twig
> +																<li>Kills to red skull: <b>{{ config.lua.dayKillsToRedSkull }}</b></li>
```suggestion
																<li>Kills to red skull: <b>{{ dayKillsToRedSkull }}</b></li>
```

2023-11-20 15:34 UTC, elsongabriel commented on system/templates/serverinfo.html.twig
> +															{%  elseif config.lua.dayKillsToRedSkull is defined or config.lua.kills_per_day_red_skull is defined %}
servidor canary não tem essa config
```suggestion
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'dailyFragsToRedSkull' => configLua('dayKillsToRedSkull') ?? null),
```suggestion
    'dailyFragsToRedSkull' => configLua('dayKillsToRedSkull') ?? null,
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'weeklyFragsToRedSkull' => configLua('weekKillsToRedSkull') ?? null),
```suggestion
    'weeklyFragsToRedSkull' => configLua('weekKillsToRedSkull') ?? null,
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
> +    'monthlyFragsToRedSkull' => configLua('monthKillsToRedSkull') ?? null),
```suggestion
    'monthlyFragsToRedSkull' => configLua('monthKillsToRedSkull') ?? null,
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
>      'dailyFragsToBlackSkull' => isset($config['lua']['dailyFragsToBlackSkull']) ? $config['lua']['dailyFragsToBlackSkull'] : (isset($config['lua']['kills_per_day_black_skull']) ? $config['lua']['kill
```suggestion
    'dailyFragsToBlackSkull' => configLua('dailyFragsToBlackSkull') ?? null,
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
>      'weeklyFragsToBlackSkull' => isset($config['lua']['weeklyFragsToBlackSkull']) ? $config['lua']['weeklyFragsToBlackSkull'] : (isset($config['lua']['kills_per_week_black_skull']) ? $config['lua']['
```suggestion
    'weeklyFragsToBlackSkull' => configLua('weeklyFragsToBlackSkull') ?? null,
```

2023-11-20 15:34 UTC, elsongabriel commented on system/pages/serverinfo.php
>      'monthlyFragsToBlackSkull' => isset($config['lua']['monthlyFragsToBlackSkull']) ? $config['lua']['monthlyFragsToBlackSkull'] : (isset($config['lua']['kills_per_month_black_skull']) ? $config['lua
```suggestion
    'monthlyFragsToBlackSkull' => configLua('monthlyFragsToBlackSkull') ?? null,
```

2023-11-20 15:40 UTC, elsongabriel commented on system/templates/serverinfo.html.twig
>  															{% endif %}
```suggestion
```

2023-11-21 12:39 UTC, elsongabriel commented on system/pages/serverinfo.php
> +$blackSkullLength = configLua('blackSkullDuration') : null;
```suggestion
$blackSkullLength = configLua('blackSkullDuration') ?? null;
```

2023-11-21 13:49 UTC, elsongabriel requested changes

2023-11-21 13:49 UTC, elsongabriel commented on templates/tibiacom/index.php
> +    </script>
preciso iniciar a tag <script> no inicio, e fechar só no fim de todas as funções.
mas onde está a função ?

```suggestion
<script>
   //         if (MediumButtonOverDownload) {
   //             MediumButtonOverDownload.style.visibility = 'hidden';
   //             // Restante do código...
   //         }
   //     }
```

2023-11-21 13:50 UTC, elsongabriel requested changes

2023-11-21 13:50 UTC, elsongabriel commented on system/templates/serverinfo.html.twig
> +    var serverSaveTime = new Date("<?php echo $serverSaveTime->format('Y-m-d G:i:s') ?>").getTime();
estamos mexendo em um arquivo .twig 
onde não há variável `$serverSaveTime` vindo do php.

essa função acaba afetando o server save box
![image](https://github.com/opentibiabr/myaac/assets/7812282/566f29e2-e046-4f48-b894-d86a5851572d)

2023-11-21 13:51 UTC, elsongabriel requested changes

2023-11-21 13:51 UTC, elsongabriel commented on system/pages/serverinfo.php
>      'ipBanishmentLength' => isset($config['lua']['ip_banishment_length']) ? eval('return (' . $config['lua']['ip_banishment_length'] . ') / (24 * 60 * 60);') : null,
nós não usamos essas configs no canary (é preciso analisar no config.lua do servidor também).
```suggestion
```

2023-11-23 12:26 UTC, majestyotbr approved these changes

2023-11-23 12:27 UTC, merged